build:
    environment:
        variables:
            DB_HOSTNAME: '127.0.0.1'
            DB_DATABASE: 'project_3s'
            DB_USERNAME: 'nayananga'
            DB_PASSWORD: ''
        php:
            version: 7.1
    project_setup:
        before:
            - mysql -e "CREATE DATABASE project_3s"
            - mysql project_3s < database/project_3s.sql
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
